import unittest
from romanos_funcion import roman_to_decimal
# En este punto no me reconoce el archivo romanos_funcion. Como se puede arreglar este
#error.

class RomanosTest(unittest.TestCase):
    def test_unidades(self):
        self.assertEqual(roman_to_decimal('I'), 1)
        self.assertEqual(roman_to_decimal('V'), 5)
        self.assertEqual(roman_to_decimal('X'), 10)
        self.assertEqual(roman_to_decimal('L'), 50)
        self.assertEqual(roman_to_decimal('C'), 100)
        self.assertEqual(roman_to_decimal('D'), 500)
        self.assertEqual(roman_to_decimal('M'), 1000)

    def test_numeros_basicos(self):
        self.assertEqual(roman_to_decimal("IV"), 4)
        self.assertEqual(roman_to_decimal("IX"), 9)
        self.assertEqual(roman_to_decimal("XL"), 40)
        self.assertEqual(roman_to_decimal("CCV"), 205)
        self.assertEqual(roman_to_decimal("MCXXIII"), 1123)

    def test_no_resta_mas_de_un_orden_de_magnitud(self):
        # self.assertRaises(ValueError, convertir_en_numero, 'IC')
        # self.assertRaises(ValueError, convertir_en_numero, 'VC')
        with self.assertRaises(ValueError):
            roman_to_decimal('IC')
        with self.assertRaises(ValueError):
            roman_to_decimal('ID')
        with self.assertRaises(ValueError):
            roman_to_decimal('VC')
        with self.assertRaises(ValueError):
            roman_to_decimal('LM')
    def test_no_restas_consecutivas(self):
        self.assertRaises(ValueError,roman_to_decimal,'CCM')
        self.assertRaises(ValueError,roman_to_decimal,'XXC')
        self.assertRaises(ValueError,roman_to_decimal,'MMCCMM')
        self.assertRaises(ValueError,roman_to_decimal,'IIV')
        self.assertRaises(ValueError,roman_to_decimal,'IIX')

    def test_no_mas_de_tres_simbolos_consecutivos(self):
        self.assertRaises(ValueError,roman_to_decimal,'MMMM')
        self.assertRaises(ValueError,roman_to_decimal,'CCCC')
        self.assertRaises(ValueError,roman_to_decimal,'XXXX')
        self.assertRaises(ValueError,roman_to_decimal,'IIII')
        self.assertRaises(ValueError,roman_to_decimal,'IIX')
unittest.main()